# Generated by Django 3.0.4 on 2020-04-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_page', '0002_auto_20200421_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rjyiyaoxpsj',
            old_name='id',
            new_name='ID',
        ),
    ]
