# Generated by Django 3.0.4 on 2020-04-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_page', '0003_auto_20200422_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='scjrmzszq',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cj', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'scjrm_zszq',
                'managed': True,
            },
        ),
    ]
