# Generated by Django 3.0.4 on 2020-05-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_page', '0005_auto_20200518_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
